export const CREATE_ANNOUNCEMENT_REQUEST = "CREATE_ANNOUNCEMENT_REQUEST";
export const CREATE_ANNOUNCEMENT_SUCCESS = "CREATE_ANNOUNCEMENT_SUCCESS";
export const CREATE_ANNOUNCEMENT_FAIL = "CREATE_ANNOUNCEMENT_FAIL";

export const ANNOUNCEMENT_LIST_REQUEST = "ANNOUNCEMENT_LIST_REQUEST";
export const ANNOUNCEMENT_LIST_SUCCESS = "ANNOUNCEMENT_LIST_SUCCESS";
export const ANNOUNCEMENT_LIST_FAIL = "ANNOUNCEMENT_LIST_FAIL";
