export const CREATE_ATTENDENCE_REQUEST = "CREATE_ATTENDENCE_REQUEST";
export const CREATE_ATTENDENCE_SUCCESS = "CREATE_ATTENDENCE_SUCCESS";
export const CREATE_ATTENDENCE_FAIL = "CREATE_ATTENDENCE_FAIL";

export const ATTENDENCE_LIST_REQUEST = "ATTENDENCE_LIST_REQUEST";
export const ATTENDENCE_LIST_SUCCESS = "ATTENDENCE_LIST_SUCCESS";
export const ATTENDENCE_LIST_FAIL = "ATTENDENCE_LIST_FAIL";
