export const CREATE_COST_REQUEST = "CREATE_COST_REQUEST";
export const CREATE_COST_SUCCESS = "CREATE_COST_SUCCESS";
export const CREATE_COST_FAIL = "CREATE_COST_FAIL";

export const COST_LIST_REQUEST = "COST_LIST_REQUEST";
export const COST_LIST_SUCCESS = "COST_LIST_SUCCESS";
export const COST_LIST_FAIL = "COST_LIST_FAIL";
