export const CREATE_LEAVES_REQUEST = "CREATE_LEAVES_REQUEST";
export const CREATE_LEAVES_SUCCESS = "CREATE_LEAVES_SUCCESS";
export const CREATE_LEAVES_FAIL = "CREATE_LEAVES_FAIL";

export const LEAVES_LIST_REQUEST = "LEAVES_LIST_REQUEST";
export const LEAVES_LIST_SUCCESS = "LEAVES_LIST_SUCCESS";
export const LEAVES_LIST_FAIL = "LEAVES_LIST_FAIL";
