export const CREATE_PAYROLL_REQUEST = "CREATE_PAYROLL_REQUEST";
export const CREATE_PAYROLL_SUCCESS = "CREATE_PAYROLL_SUCCESS";
export const CREATE_PAYROLL_FAIL = "CREATE_PAYROLL_FAIL";

export const PAYROLL_LIST_REQUEST = "PAYROLL_LIST_REQUEST";
export const PAYROLL_LIST_SUCCESS = "PAYROLL_LIST_SUCCESS";
export const PAYROLL_LIST_FAIL = "PAYROLL_LIST_FAIL";
